[BITS 16] 

Date:
	MOV AH, 0x04
	INT 0x1A
	RET
	;CH - CENTURY
	;CL - YEAR
	;DH - MONTH
	;DL - DAY
Convert_month:
	MOV BH,DH
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [DATE_FIELD],BH
	MOV BH,DH
	AND BH,0FH
	ADD BH,30H
	MOV [DATE_FIELD + 1],BH
	RET
Convert_day:
	MOV BH,DL
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [DATE_FIELD],BH
	MOV BH,DL
	AND BH,0FH
	ADD BH,30H
	MOV [DATE_FIELD +4],BH
	RET
Convert_century:
	MOV BH,CH
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [DATE_FIELD],BH
	MOV BH,CH
	AND BH,0FH
	ADD BH,30H
	MOV [DATE_FIELD + 7],BH
	RET
Convert_year:
	MOV BH,CL
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [DATE_FIELD],BH
	MOV BH,CL
	AND BH,0FH
	ADD BH,30H
	MOV [DATE_FIELD + 9],BH
	RET
Display_date:
	MOV AH,13H ;FUNCTION 13H (DISPLAY STRING)
	MOV AL,0 ;WRITE MODE IS ZERO
	MOV BH,0 ;USE VIDEO PAGE OF ZERO
	MOV BL,0FH ;ATTRIBUTE
	MOV CX,10 ;CHARACTER STRING IS 10 LONG
	MOV DH,5 ;POSITION ON ROW 4
	MOV DL,0 ;AND COLUMN 28
	PUSH DS ;PUT DS REGISTER ON STACK
	POP ES ;POP IT INTO ES REGISTER
	LEA BP,[DATE_FIELD] ;LOAD THE OFFSET ADDRESS OF STRING INTO BP
	INT 10H
	RET
Time:
	MOV AH,02H
	INT 1AH
	RET
	;CH - HOURS
	;CL - MINUTES
	;DH - SECONDS
Convert_hours:
	MOV BH,CH
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [TIME_FIELD],BH
	MOV BH,CH
	AND BH,0FH
	ADD BH,30H
	MOV [TIME_FIELD + 1],BH
	RET
Convert_minutes:
	MOV BH,CL
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [TIME_FIELD],BH
	MOV BH,CL
	AND BH,0FH
	ADD BH,30H
	MOV [TIME_FIELD + 4],BH
	RET
Convert_seconds:
	MOV BH,DH
	SHR BH,1
	SHR BH,1
	SHR BH,1
	SHR BH,1
	ADD BH,30H
	MOV [TIME_FIELD],BH
	MOV BH,DH
	AND BH,0FH
	ADD BH,30H
	MOV [TIME_FIELD + 7],BH
	RET
Display_time:
	MOV AH,13H ;FUNCTION 13H (DISPLAY STRING)
	MOV AL,0 ;WRITE MODE IS ZERO
	MOV BH,0 ;USE VIDEO PAGE OF ZERO
	MOV BL,0FH ;ATTRIBUTE
	MOV CX,8 ;CHARACTER STRING IS 8 LONG
	MOV DH,5 ;POSITION ON ROW 5
	MOV DL,0 ;AND COLUMN 28
	PUSH DS ;PUT DS REGISTER ON STACK
	POP ES ;POP IT INTO ES REGISTER
	LEA BP,[TIME_FIELD] ;LOAD THE OFFSET ADDRESS OF STRING INTO BP
	INT 10H
	RET



DATE_FIELD: DB '00/00/0000', 0
TIME_FIELD: DB '00:00:00', 0
